setup: true
jobs:
  setup:
      docker:
        - image: circleci/golang:latest
      steps:
        - checkout
        - run:
           name: Grab remote config and execute in new workflow
           command: |
             git clone https://github.com/PK1312/ca-dynamic-config-central.git
        - continuation/continue:
            configuration_path: ca-dynamic-config-central/remoteconfig.yml

orbs:
  go: circleci/go@1.6.0
  continuation: circleci/continuation@0.1.2
version: 2.1
workflows:
  setup:
    jobs:
      - setup
